### ISSUE TITLE
老哥可以请教一下是如何关闭cfg的吗？

### ISSUE THREAD

**Issue by mianmian7** [monotone/hackintosh-oc-efi-b660m-terminator-12400-rx6600xt#1]
我是12490F+铭瑄B660M终结者
我在网上找了很多方法都不行。用oc的ControlMsrE2.efi无法解锁，只能查看状态，还是锁着的。

**Comment by monotone** [comment]
/EFI/OC/Tools/CFGLock.efi 这个工具可以解决，还有ControlMsrE2.efi。虽然查看资料收后者是前者的升级，但是貌似后者只能查看不能修改，我是用前者修改后者查看的。

**Comment by mianmian7** [comment]
> 

谢谢老哥回复，我也试过CFGLock.efi，会显示Couldn't find any Varlable with cfg in name.
BIOS版本是H3.7G，今年7月份的版本
我也试过用modGRUBShell.efi把软件搜到的cfglock地址0x44设成0，但用ControlMsrE2.efi查还是锁着的。
不过用起来一切都正常就是了，好像没解也没很大关系

**Comment by monotone** [comment]
> 

我是进的 openshell.efi 直接调用controlmsre2.efi改过一次，也用cfglock改过一次，最终就成功了。感觉没改只要能进系统区别也没那么大
